export enum StorageKeys {
    LOGGER_ID = "loggerId",
    EMAIL = "email",
    USER_ID = "userId",
    POS = "pos",
    CLUSTER = "cluster",
    ACTIVE = "active",
    DEPARTMENT = "department",
    ROLE = "role",
    SYSTEM_DATE = "systemDate",
    USER_LEVEL = "user_level",
    YIELD_BRANDS = "yieldBrands",
    EXCHANGE_RATES = "exchangeRates",
    SIGNIFICANT_LIST = "significantList",
    USER_ACCESS_LIST = "userAccessList",
    JUP_MODULES_LIST = "modulesList",
    DECIMAL_POINTS = "decimalPoints",
    IS_ANALYST_DASHBOARD = "isAnalystDashboard",
    ACCESS_LIST = "accessList",
    WEIGHTAGE_PAYLOAD = "weightagePayload",
    USER_NAME = "user",
    ASMI_THEM = "ASMI_THEM"
}